"use client";

import * as React from "react";
import Link from "next/link";
import { ArrowRight, Brain, CreditCard, Dumbbell, Users, Wallet, AlertTriangle } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { api, ApiError } from "@/lib/api/client";

type OwnerBriefing = { generatedAt: string; metrics: { members: number; activeMemberships: number; todayAttendance: number; todayRevenue: number; expiringSoon: number; outstandingPayments: number }; alerts: { id: string; severity: "high" | "medium" | "low"; title: string; detail: string; href?: string }[]; recommendations: { id: string; title: string; reason: string; href?: string }[] };
function money(value: number) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value); }

export default function OwnerOsPage() {
  const [data, setData] = React.useState<OwnerBriefing | null>(null);
  const [error, setError] = React.useState<string | null>(null);
  React.useEffect(() => { let active = true; api.get<OwnerBriefing>("/owner-os/briefing").then(v => active && setData(v)).catch(e => active && setError(e instanceof ApiError ? e.message : "Unable to load owner briefing")); return () => { active = false; }; }, []);
  if (error) return <Card><CardContent className="p-6 text-sm text-destructive">{error}</CardContent></Card>;
  if (!data) return <div className="grid gap-4 md:grid-cols-3"><Card className="h-28 animate-pulse" /><Card className="h-28 animate-pulse" /><Card className="h-28 animate-pulse" /></div>;
  const cards = [[Users,"Members",data.metrics.members.toLocaleString()],[CreditCard,"Active memberships",data.metrics.activeMemberships.toLocaleString()],[Dumbbell,"Today's attendance",data.metrics.todayAttendance.toLocaleString()],[Wallet,"Today's revenue",money(data.metrics.todayRevenue)],[AlertTriangle,"Expiring in 7 days",data.metrics.expiringSoon.toLocaleString()],[CreditCard,"Outstanding payments",money(data.metrics.outstandingPayments)]] as const;
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary">OWNER OS</p><h1 className="text-3xl font-semibold tracking-tight">Your gym, at a glance.</h1><p className="text-muted-foreground">AI turns today's operational data into priorities and next actions.</p></div><Button asChild><Link href="/ai"><Brain className="size-4" /> Ask AI</Link></Button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([Icon,label,value])=><Card key={label}><CardContent className="flex items-center gap-4 p-5"><div className="rounded-xl bg-primary/10 p-3 text-primary"><Icon className="size-5" /></div><div><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-semibold">{value}</p></div></CardContent></Card>)}</div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Attention required</CardTitle></CardHeader><CardContent className="space-y-3">{data.alerts.length===0?<p className="text-sm text-muted-foreground">No urgent issues detected.</p>:data.alerts.map(a=><div key={a.id} className="flex items-start justify-between gap-3 rounded-lg border p-3"><div><div className="flex items-center gap-2"><Badge variant={a.severity==="high"?"destructive":"secondary"}>{a.severity}</Badge><span className="font-medium">{a.title}</span></div><p className="mt-1 text-sm text-muted-foreground">{a.detail}</p></div>{a.href&&<Button asChild variant="ghost" size="icon"><Link href={a.href} aria-label={`Open ${a.title}`}><ArrowRight className="size-4" /></Link></Button>}</div>)}</CardContent></Card><Card><CardHeader><CardTitle>AI recommendations</CardTitle></CardHeader><CardContent className="space-y-3">{data.recommendations.length===0?<p className="text-sm text-muted-foreground">No recommendations yet.</p>:data.recommendations.map(i=><div key={i.id} className="rounded-lg border p-3"><p className="font-medium">{i.title}</p><p className="mt-1 text-sm text-muted-foreground">{i.reason}</p>{i.href&&<Button asChild variant="link" className="mt-1 h-auto px-0"><Link href={i.href}>Review <ArrowRight className="ml-1 size-3" /></Link></Button>}</div>)}</CardContent></Card></div><p className="text-xs text-muted-foreground">Briefing generated {new Date(data.generatedAt).toLocaleString("en-IN")}. AI recommendations are advisory until an authorized user approves an action.</p></div>;
}
