"use client";

import * as React from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { ArrowRight, CreditCard, Plus, Sparkles, Undo2, Wallet, TrendingUp, Clock3 } from "lucide-react";
import type { ColumnDef } from "@tanstack/react-table";
import { PageHeader } from "@/components/shared/page-header";
import { DataTable } from "@/components/shared/data-table";
import { MemberPicker } from "@/components/shared/member-picker";
import { StatCard } from "@/components/shared/stat-card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useAuth } from "@/lib/auth/auth-context";
import { usePayments, useCreatePayment, useRefundPayment } from "@/lib/hooks/use-payments";
import { ApiError } from "@/lib/api/client";
import { createPaymentSchema, refundPaymentSchema, type CreatePaymentInput, type RefundPaymentInput } from "@/lib/validation/gym";
import type { Payment, PaymentStatus } from "@/lib/types/gym";

const statusVariant: Record<PaymentStatus, "success" | "warning" | "secondary"> = { COMPLETED: "success", PARTIALLY_REFUNDED: "warning", REFUNDED: "secondary" };

function RecordPaymentDialog() {
  const [open, setOpen] = React.useState(false); const [member, setMember] = React.useState<{ id: string; label: string } | null>(null); const createPayment = useCreatePayment();
  const form = useForm<Omit<CreatePaymentInput, "memberId">>({ resolver: zodResolver(createPaymentSchema.omit({ memberId: true })), defaultValues: { amount: 0, method: "CASH", note: "" } });
  async function onSubmit(values: Omit<CreatePaymentInput, "memberId">) { if (!member) { toast.error("Select a member first"); return; } try { await createPayment.mutateAsync({ ...values, memberId: member.id }); toast.success(`Payment recorded for ${member.label}`); setOpen(false); setMember(null); form.reset(); } catch (error) { toast.error(error instanceof ApiError ? error.message : "Failed to record payment"); } }
  return <Dialog open={open} onOpenChange={(next) => { setOpen(next); if (!next) { setMember(null); form.reset(); } }}><DialogTrigger asChild><Button className="rounded-xl"><Plus /> Record payment</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Record a payment</DialogTitle></DialogHeader><div className="flex flex-col gap-4"><div><p className="mb-1.5 text-sm font-medium">Member</p><MemberPicker value={member} onChange={setMember} /></div><Form {...form}><form onSubmit={form.handleSubmit(onSubmit)} className="flex flex-col gap-4"><div className="grid grid-cols-2 gap-4"><FormField control={form.control} name="amount" render={({ field }) => <FormItem><FormLabel>Amount</FormLabel><FormControl><Input type="number" step="0.01" {...field} /></FormControl><FormMessage /></FormItem>} /><FormField control={form.control} name="method" render={({ field }) => <FormItem><FormLabel>Method</FormLabel><Select value={field.value} onValueChange={field.onChange}><FormControl><SelectTrigger className="w-full"><SelectValue /></SelectTrigger></FormControl><SelectContent><SelectItem value="CASH">Cash</SelectItem><SelectItem value="CARD">Card</SelectItem><SelectItem value="UPI">UPI</SelectItem><SelectItem value="BANK_TRANSFER">Bank transfer</SelectItem><SelectItem value="OTHER">Other</SelectItem></SelectContent></Select><FormMessage /></FormItem>} /></div><FormField control={form.control} name="note" render={({ field }) => <FormItem><FormLabel>Note (optional)</FormLabel><FormControl><Input placeholder="PT session, product sale, ..." {...field} /></FormControl><FormMessage /></FormItem>} /><DialogFooter><Button type="submit" disabled={createPayment.isPending}>{createPayment.isPending ? "Recording..." : "Record payment"}</Button></DialogFooter></form></Form></div></DialogContent></Dialog>;
}
function RefundDialog({ payment }: { payment: Payment }) { const [open, setOpen] = React.useState(false); const refundPayment = useRefundPayment(); const form = useForm<RefundPaymentInput>({ resolver: zodResolver(refundPaymentSchema), defaultValues: { amount: undefined, reason: "" } }); const alreadyRefunded = (payment.refunds ?? []).reduce((sum, r) => sum + Number(r.amount), 0); const remaining = Number(payment.amount) - alreadyRefunded; async function onSubmit(values: RefundPaymentInput) { try { await refundPayment.mutateAsync({ id: payment.id, input: values }); toast.success("Refund recorded"); setOpen(false); form.reset(); } catch (error) { toast.error(error instanceof ApiError ? error.message : "Refund failed"); } } return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="ghost" size="sm"><Undo2 className="size-3.5" /> Refund</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Refund payment</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Remaining refundable balance: {payment.currency} {remaining.toFixed(2)}</p><Form {...form}><form onSubmit={form.handleSubmit(onSubmit)} className="flex flex-col gap-4"><FormField control={form.control} name="amount" render={({ field }) => <FormItem><FormLabel>Amount</FormLabel><FormControl><Input type="number" step="0.01" placeholder={remaining.toFixed(2)} {...field} value={field.value ?? ""} /></FormControl><FormMessage /></FormItem>} /><FormField control={form.control} name="reason" render={({ field }) => <FormItem><FormLabel>Reason (optional)</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>} /><DialogFooter><Button type="submit" variant="destructive" disabled={refundPayment.isPending}>{refundPayment.isPending ? "Refunding..." : "Issue refund"}</Button></DialogFooter></form></Form></DialogContent></Dialog>; }
function RefundCell({ payment }: { payment: Payment }) { const { hasPermission } = useAuth(); if (payment.status === "REFUNDED") return <span className="text-xs text-muted-foreground">Fully refunded</span>; if (!hasPermission("payments.refund")) return null; return <RefundDialog payment={payment} />; }
const columns: ColumnDef<Payment>[] = [
  { header: "Member", accessorKey: "member", cell: ({ row }) => { const m = row.original.member; return m ? <div><p className="font-semibold">{m.firstName} {m.lastName}</p><p className="text-xs text-muted-foreground">{row.original.note ?? "Payment"}</p></div> : "—"; } },
  { header: "Amount", accessorKey: "amount", cell: ({ row }) => <span className="font-semibold tabular-nums">{row.original.currency} {row.original.amount}</span> },
  { header: "Method", accessorKey: "method", cell: ({ row }) => <Badge variant="outline">{row.original.method}</Badge> },
  { header: "Status", accessorKey: "status", cell: ({ row }) => <Badge variant={statusVariant[row.original.status]}>{row.original.status}</Badge> },
  { header: "Date", accessorKey: "createdAt", cell: ({ row }) => <span className="text-sm text-muted-foreground">{new Date(row.original.createdAt).toLocaleString()}</span> },
  { id: "actions", header: "", cell: ({ row }) => <RefundCell payment={row.original} /> },
];
export default function BillingPage() {
  const { hasPermission } = useAuth(); const [page, setPage] = React.useState(1); const paymentsQuery = usePayments({ page, pageSize: 20, order: "desc" }); const items = paymentsQuery.data?.items ?? [];
  const totalCollected = items.filter((p) => p.status !== "REFUNDED").reduce((sum, p) => sum + Number(p.amount), 0); const totalRefunded = items.flatMap((p) => p.refunds ?? []).reduce((sum, r) => sum + Number(r.amount), 0); const currency = items[0]?.currency ?? "INR";
  return <div className="flex flex-col gap-7">
    <PageHeader title="Finance OS" description="Track collections, refunds and payment activity with financial context." actions={hasPermission("payments.create") && <RecordPaymentDialog />} />
    <section className="relative overflow-hidden rounded-3xl border border-primary/15 bg-gradient-to-br from-primary/[0.10] via-card to-card p-6 shadow-sm sm:p-8"><div className="pointer-events-none absolute -right-20 -top-24 size-64 rounded-full bg-primary/10 blur-3xl" /><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-primary/15 bg-background/70 px-3 py-1.5 text-xs font-semibold text-primary"><Sparkles className="size-3.5" /> Finance intelligence</div><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">Know where the money moved.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">A clean operating view for collections, refunds and payment activity. No fabricated aggregates—only data available to the current finance API.</p></div><Button asChild variant="outline" className="rounded-xl bg-background/60"><a href="/ai"><Sparkles className="size-4" /> Ask AI about revenue</a></Button></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Collected · current page" icon={Wallet} value={`${currency} ${totalCollected.toFixed(2)}`} isLoading={paymentsQuery.isLoading} tone="success" /><StatCard title="Refunded · current page" icon={Undo2} value={`${currency} ${totalRefunded.toFixed(2)}`} isLoading={paymentsQuery.isLoading} tone="warning" /><StatCard title="Transactions" icon={CreditCard} value={items.length} isLoading={paymentsQuery.isLoading} tone="primary" /><StatCard title="Payment activity" icon={TrendingUp} value="Live" isLoading={paymentsQuery.isLoading} /></section>
    <section className="grid gap-3 sm:grid-cols-3"><FinanceInsight icon={TrendingUp} title="Revenue trend" text="Period-level revenue analytics can be connected here when the backend aggregate is available." /><FinanceInsight icon={Clock3} title="Outstanding" text="Next layer: aging, renewal balances and recovery opportunities from real billing data." /><FinanceInsight icon={Sparkles} title="AI finance" text="Next layer: explain revenue changes and surface high-impact financial actions." /></section>
    <Card className="overflow-hidden border-0 shadow-sm ring-1 ring-border/70"><CardHeader className="border-b bg-muted/20"><div className="flex items-center justify-between"><div><CardTitle className="text-base">Payment activity</CardTitle><p className="mt-1 text-xs text-muted-foreground">Current transactions and refund actions.</p></div><Badge variant="outline">Page {page}</Badge></div></CardHeader><CardContent className="p-0"><DataTable columns={columns} data={paymentsQuery.data} isLoading={paymentsQuery.isLoading} isError={paymentsQuery.isError} onRetry={() => paymentsQuery.refetch()} page={page} onPageChange={setPage} emptyTitle="No payments recorded yet" emptyDescription="Record your first payment to start tracking gym revenue." /></CardContent></Card></section>
  </div>;
}
function FinanceInsight({ icon: Icon, title, text }: { icon: typeof TrendingUp; title: string; text: string }) { return <Card className="border-0 shadow-sm ring-1 ring-border/70"><CardContent className="p-4"><span className="flex size-9 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="size-4" /></span><p className="mt-3 text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p><span className="mt-3 inline-flex items-center gap-1 text-[11px] font-medium text-primary">Planned next <ArrowRight className="size-3" /></span></CardContent></Card>; }
