"use client";

import Link from "next/link";
import * as React from "react";
import { ArrowRight, CalendarCheck, CheckCircle2, ClipboardCheck, Dumbbell, Sparkles, UserRound, Users, WalletCards, Zap } from "lucide-react";
import { toast } from "sonner";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/lib/auth/auth-context";
import { useUpdateWorkoutAssignmentStatus, useWorkoutAssignments } from "@/lib/hooks/use-workouts";
import type { WorkoutAssignment } from "@/lib/types/gym";
import { ApiError } from "@/lib/api/client";
import { PtPackagesSection } from "./pt-packages-section";

const tones = {
  cyan: "from-cyan-50 to-sky-50 text-cyan-700",
  emerald: "from-emerald-50 to-teal-50 text-emerald-700",
  amber: "from-amber-50 to-orange-50 text-amber-700",
  violet: "from-violet-50 to-fuchsia-50 text-violet-700",
};

function Metric({ icon: Icon, label, value, hint, tone }: { icon: typeof Users; label: string; value: React.ReactNode; hint: string; tone: keyof typeof tones }) {
  return <Card className="group relative overflow-hidden border-white/90 bg-white/85 shadow-[0_20px_60px_-38px_rgba(79,70,229,.35)] backdrop-blur-xl transition hover:-translate-y-1 hover:shadow-[0_28px_70px_-38px_rgba(79,70,229,.42)]"><div className="pointer-events-none absolute -right-8 -top-8 size-28 rounded-full bg-primary/10 blur-2xl" /><CardContent className="relative flex items-center gap-4 p-5"><span className={`flex size-14 shrink-0 items-center justify-center rounded-[19px] bg-gradient-to-br shadow-sm ${tones[tone]}`}><Icon className="size-6" /></span><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[.18em] text-stone-400">{label}</p><p className="mt-1 text-2xl font-black tracking-tight text-stone-950">{value}</p><p className="mt-1 text-[11px] font-medium text-stone-400">{hint}</p></div></CardContent></Card>;
}

function AssignmentRow({ assignment }: { assignment: WorkoutAssignment }) {
  const { hasPermission } = useAuth();
  const updateStatus = useUpdateWorkoutAssignmentStatus();
  const member = assignment.member;
  async function complete() { try { await updateStatus.mutateAsync({ id: assignment.id, status: "COMPLETED" }); toast.success("Workout assignment marked complete"); } catch (error) { toast.error(error instanceof ApiError ? error.message : "Failed to update assignment"); } }
  return <div className="group flex flex-col gap-4 rounded-[22px] border border-stone-200/80 bg-white/70 p-4 transition hover:-translate-y-0.5 hover:border-violet-200 hover:bg-white hover:shadow-lg sm:flex-row sm:items-center"><div className="flex min-w-0 flex-1 items-center gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-[15px] bg-gradient-to-br from-cyan-100 to-violet-100 text-violet-700"><UserRound className="size-5" /></span><div className="min-w-0"><p className="truncate text-sm font-extrabold text-stone-900">{member ? `${member.firstName} ${member.lastName}` : "Member unavailable"}</p><p className="truncate text-xs font-medium text-stone-500">{assignment.workoutPlan?.name ?? "Workout plan unavailable"}</p></div></div><div className="flex items-center gap-3 text-xs font-semibold text-stone-500"><span>{new Date(assignment.startDate).toLocaleDateString(undefined,{day:"numeric",month:"short"})}</span><Badge variant={assignment.status === "ACTIVE" ? "default" : assignment.status === "COMPLETED" ? "success" : "secondary"}>{assignment.status}</Badge></div><div className="flex gap-2"><Button asChild variant="ghost" size="sm"><Link href={member ? `/members/${member.id}` : "/members"}>Client <ArrowRight className="size-3.5" /></Link></Button>{assignment.status === "ACTIVE" && hasPermission("workouts.assign") && <Button size="sm" variant="outline" disabled={updateStatus.isPending} onClick={complete}><CheckCircle2 className="size-4" />{updateStatus.isPending ? "Saving..." : "Complete"}</Button>}</div></div>;
}

export default function PtoOperationsPage() {
  const assignmentsQuery = useWorkoutAssignments({ page: 1, pageSize: 50, order: "desc" });
  const assignments = assignmentsQuery.data?.items ?? [];
  const active = assignments.filter(x => x.status === "ACTIVE");
  const completed = assignments.filter(x => x.status === "COMPLETED");
  const clients = new Set(active.map(x => x.memberId)).size;
  const plans = new Set(active.map(x => x.workoutPlanId)).size;
  return <div className="relative -mx-2 min-h-full overflow-hidden pb-12 sm:-mx-3 lg:-mx-5"><div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(circle_at_5%_2%,rgba(6,182,212,.13),transparent_19%),radial-gradient(circle_at_96%_4%,rgba(99,102,241,.15),transparent_22%),radial-gradient(circle_at_70%_38%,rgba(217,70,239,.10),transparent_25%),radial-gradient(circle_at_12%_72%,rgba(16,185,129,.08),transparent_24%)]" /><div className="mx-auto flex max-w-[1680px] flex-col gap-8 px-2 sm:px-4 lg:px-6">
    <section className="group relative overflow-hidden rounded-[34px] border border-white/90 bg-white/88 p-6 shadow-[0_35px_110px_-48px_rgba(79,70,229,.48)] backdrop-blur-2xl sm:p-8 lg:p-10"><div className="pointer-events-none absolute -left-24 -top-32 size-80 rounded-full bg-cyan-300/25 blur-3xl" /><div className="pointer-events-none absolute -right-28 -top-24 size-96 rounded-full bg-violet-300/25 blur-3xl" /><div className="pointer-events-none absolute -bottom-40 left-[35%] size-96 rounded-full bg-fuchsia-300/15 blur-3xl" /><div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-violet-100 bg-white/75 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.18em] text-violet-700"><Sparkles className="size-3.5" /> Training command center</div><h1 className="font-serif text-4xl font-semibold tracking-[-.045em] text-stone-950 sm:text-5xl lg:text-6xl">PT OS</h1><p className="mt-3 max-w-2xl text-sm font-medium leading-6 text-stone-500">Your coaching cockpit for active assignments, clients, sessions and workout execution.</p></div><div className="flex flex-wrap gap-3"><Button asChild variant="outline" className="rounded-2xl border-stone-200 bg-white/80"><Link href="/workouts"><Dumbbell className="size-4" /> Manage workouts</Link></Button><Button asChild className="rounded-2xl bg-[linear-gradient(105deg,#4338ca,#7c3aed_52%,#c026d3)] shadow-lg shadow-violet-500/20"><Link href="/ai"><Sparkles className="size-4" /> Ask AI Coach <ArrowRight className="size-4" /></Link></Button></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={ClipboardCheck} label="Active assignments" value={assignmentsQuery.isLoading ? "—" : active.length} hint="Current coaching workload" tone="cyan" /><Metric icon={Users} label="Active clients" value={assignmentsQuery.isLoading ? "—" : clients} hint="Members in active plans" tone="emerald" /><Metric icon={CheckCircle2} label="Completed" value={assignmentsQuery.isLoading ? "—" : completed.length} hint="Finished assignments" tone="amber" /><Metric icon={Dumbbell} label="Plans in workload" value={assignmentsQuery.isLoading ? "—" : plans} hint="Programs being delivered" tone="violet" /></section>
    <section className="grid gap-5 xl:grid-cols-[1.35fr_.8fr]"><Card className="overflow-hidden border-white/90 bg-white/88 shadow-xl shadow-violet-900/5 backdrop-blur-xl"><CardHeader className="border-b border-stone-100/80 bg-gradient-to-r from-white via-cyan-50/40 to-violet-50/50 px-5 py-5"><CardTitle className="flex items-center gap-3 font-serif text-xl text-stone-950"><span className="flex size-10 items-center justify-center rounded-xl bg-gradient-to-br from-cyan-100 to-violet-100 text-violet-700"><Zap className="size-4" /></span>Active coaching queue</CardTitle><p className="mt-1 text-xs font-medium text-stone-500">The clients and programs that need trainer attention.</p></CardHeader><CardContent className="p-3 sm:p-4">{assignmentsQuery.isError ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm font-semibold text-rose-700">Unable to load PT assignments. Refresh and try again.</div> : active.length === 0 && !assignmentsQuery.isLoading ? <div className="rounded-2xl border border-dashed border-stone-200 bg-stone-50/70 p-10 text-center"><ClipboardCheck className="mx-auto size-8 text-stone-400" /><p className="mt-3 text-sm font-bold text-stone-900">No active PT assignments</p><p className="mt-1 text-xs text-stone-500">Assign a workout plan to start the coaching workload.</p><Button asChild className="mt-4 rounded-xl"><Link href="/workouts">Assign a workout</Link></Button></div> : <div className="flex flex-col gap-3">{active.map(x => <AssignmentRow key={x.id} assignment={x} />)}</div>}</CardContent></Card>
      <Card className="overflow-hidden border-0 bg-[linear-gradient(145deg,#172554,#3730a3_45%,#a21caf)] text-white shadow-[0_28px_75px_-38px_rgba(79,70,229,.78)]"><CardHeader className="border-b border-white/10"><CardTitle className="flex items-center gap-3 font-serif text-xl"><span className="flex size-10 items-center justify-center rounded-xl bg-white/10"><Sparkles className="size-4" /></span>Coach focus</CardTitle><p className="mt-1 text-xs text-white/60">Fast routes from planning to execution.</p></CardHeader><CardContent className="space-y-3 p-5"><Focus icon={CalendarCheck} title="Today&apos;s sessions" text="Open the live PT calendar and close sessions as they happen." href="/pt-operations/sessions" /><Focus icon={UserRound} title="Client context" text="Jump into Member 360 before changing a program." href="/members" /><Focus icon={Dumbbell} title="Workout studio" text="Build, assign and manage training plans." href="/workouts" /><Link href="/ai" className="flex items-center justify-between rounded-2xl bg-white p-3.5 text-xs font-extrabold text-indigo-800 shadow-lg">Open AI Coach <ArrowRight className="size-4" /></Link></CardContent></Card></section>
    <PtPackagesSection />
    <Card className="overflow-hidden border-white/90 bg-white/85 shadow-lg backdrop-blur-xl"><CardHeader><CardTitle className="font-serif text-xl text-stone-950">Recent completions</CardTitle></CardHeader><CardContent>{completed.length === 0 ? <p className="text-sm font-medium text-stone-500">No completed assignments in the current workload window.</p> : <div className="flex flex-col gap-3">{completed.slice(0,10).map(x => <AssignmentRow key={x.id} assignment={x} />)}</div>}</CardContent></Card>
  </div></div>;
}

function Focus({ icon: Icon, title, text, href }: { icon: typeof CalendarCheck; title: string; text: string; href: string }) { return <Link href={href} className="group rounded-2xl border border-white/10 bg-white/10 p-4 backdrop-blur transition hover:bg-white/15"><Icon className="size-4 text-white/80" /><p className="mt-2 text-sm font-extrabold">{title}</p><p className="mt-1 text-xs leading-5 text-white/60">{text}</p><span className="mt-2 inline-flex items-center gap-1 text-[10px] font-bold text-white/80">Open <ArrowRight className="size-3 transition group-hover:translate-x-1" /></span></Link>; }
