"use client";

import Link from "next/link";
import * as React from "react";
import { ArrowRight, CalendarDays, CheckCircle2, ClipboardCheck, Dumbbell, Sparkles, UserRound, Users, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { StatCard } from "@/components/shared/stat-card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/lib/auth/auth-context";
import { useUpdateWorkoutAssignmentStatus, useWorkoutAssignments } from "@/lib/hooks/use-workouts";
import type { WorkoutAssignment } from "@/lib/types/gym";
import { ApiError } from "@/lib/api/client";

function formatDate(value: string) { return new Date(value).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" }); }
function AssignmentRow({ assignment }: { assignment: WorkoutAssignment }) { const { hasPermission } = useAuth(); const updateStatus = useUpdateWorkoutAssignmentStatus(); const member = assignment.member; const plan = assignment.workoutPlan; async function markComplete() { try { await updateStatus.mutateAsync({ id: assignment.id, status: "COMPLETED" }); toast.success("Workout assignment marked complete"); } catch (error) { toast.error(error instanceof ApiError ? error.message : "Failed to update assignment"); } } return <div className="group flex flex-col gap-3 rounded-2xl border p-4 transition hover:border-primary/20 hover:bg-muted/20 sm:flex-row sm:items-center"><div className="flex min-w-0 flex-1 items-center gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><UserRound className="size-5" /></div><div className="min-w-0"><p className="truncate font-semibold">{member ? `${member.firstName} ${member.lastName}` : "Member unavailable"}</p><p className="truncate text-sm text-muted-foreground">{plan?.name ?? "Workout plan unavailable"}</p></div></div><div className="flex items-center gap-3 text-sm text-muted-foreground"><span>{formatDate(assignment.startDate)}</span><Badge variant={assignment.status === "ACTIVE" ? "default" : assignment.status === "COMPLETED" ? "success" : "secondary"}>{assignment.status}</Badge></div><div className="flex items-center gap-2 sm:ml-2">{member && <Button asChild variant="ghost" size="sm"><Link href={`/members/${member.id}`}>Client <ArrowRight className="size-3.5" /></Link></Button>}{assignment.status === "ACTIVE" && hasPermission("workouts.assign") && <Button variant="outline" size="sm" disabled={updateStatus.isPending} onClick={markComplete}><CheckCircle2 className="size-4" />{updateStatus.isPending ? "Saving..." : "Complete"}</Button>}</div></div>; }
export default function PtoOperationsPage() { const assignmentsQuery = useWorkoutAssignments({ page: 1, pageSize: 50, order: "desc" }); const assignments = assignmentsQuery.data?.items ?? []; const active = assignments.filter((item) => item.status === "ACTIVE"); const completed = assignments.filter((item) => item.status === "COMPLETED"); const uniqueMembers = new Set(active.map((item) => item.memberId)).size; return <div className="flex flex-col gap-7">
  <section className="relative overflow-hidden rounded-3xl border border-primary/15 bg-gradient-to-br from-primary/[0.10] via-card to-card p-6 shadow-sm sm:p-8"><div className="pointer-events-none absolute -right-20 -top-24 size-64 rounded-full bg-primary/10 blur-3xl" /><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-primary/15 bg-background/70 px-3 py-1.5 text-xs font-semibold text-primary"><Sparkles className="size-3.5" /> Coaching workspace</div><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">PT OS</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Run today&apos;s coaching workload, open the member context, and move from assignment to action.</p></div><div className="flex flex-wrap gap-2"><Button asChild variant="outline" className="rounded-xl bg-background/60"><Link href="/workouts"><Dumbbell className="size-4" /> Manage workouts</Link></Button><Button asChild className="rounded-xl"><Link href="/ai"><Sparkles className="size-4" /> Ask AI Coach</Link></Button></div></div></section>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Active assignments" icon={ClipboardCheck} value={active.length} isLoading={assignmentsQuery.isLoading} /><StatCard title="Active clients" icon={Users} value={uniqueMembers} isLoading={assignmentsQuery.isLoading} tone="primary" /><StatCard title="Completed" icon={CheckCircle2} value={completed.length} isLoading={assignmentsQuery.isLoading} tone="success" /><StatCard title="Plans in workload" icon={Dumbbell} value={new Set(active.map((item) => item.workoutPlanId)).size} isLoading={assignmentsQuery.isLoading} /></div>
  <section className="grid gap-4 xl:grid-cols-[1.5fr_1fr]"><Card className="border-0 shadow-sm ring-1 ring-border/70"><CardHeader className="border-b bg-muted/20"><div className="flex items-center justify-between"><div><CardTitle className="text-base">Today&apos;s coaching workload</CardTitle><p className="mt-1 text-xs text-muted-foreground">Assignments currently requiring trainer attention.</p></div><Badge variant="outline">{active.length} active</Badge></div></CardHeader><CardContent className="p-3 sm:p-4">{assignmentsQuery.isError ? <div className="rounded-2xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">Unable to load PT assignments. Refresh and try again.</div> : active.length === 0 && !assignmentsQuery.isLoading ? <div className="rounded-2xl border border-dashed p-8 text-center"><ClipboardCheck className="mx-auto size-8 text-muted-foreground" /><p className="mt-3 font-medium">No active PT assignments</p><p className="mt-1 text-sm text-muted-foreground">Assign a workout plan to start building the coaching workload.</p><Button asChild className="mt-4"><Link href="/workouts">Assign a workout</Link></Button></div> : <div className="flex flex-col gap-3">{active.map((assignment) => <AssignmentRow key={assignment.id} assignment={assignment} />)}</div>}</CardContent></Card>
  <Card className="border-0 bg-gradient-to-br from-violet-500/[0.08] via-card to-card shadow-sm ring-1 ring-primary/15"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Sparkles className="size-4 text-primary" /> AI Coach focus</CardTitle></CardHeader><CardContent className="space-y-3"><Focus icon={CalendarDays} title="Today&apos;s sessions" text="Use the active workload as the starting point for coaching execution." /><Focus icon={UserRound} title="Client context" text="Open Member 360 before changing a plan or making a recommendation." /><Focus icon={WalletCards} title="PT business" text="Package, session usage and trainer commission data should become the next PT commerce layer." /><Link href="/ai" className="flex items-center justify-between rounded-xl border bg-background/60 p-3 text-xs font-semibold hover:bg-background">Open AI Coach <ArrowRight className="size-4" /></Link></CardContent></Card></section>
  <Card className="border-0 shadow-sm ring-1 ring-border/70"><CardHeader><CardTitle className="text-base">Recent completions</CardTitle></CardHeader><CardContent>{completed.length === 0 ? <p className="text-sm text-muted-foreground">No completed assignments in the current workload window.</p> : <div className="flex flex-col gap-3">{completed.slice(0, 10).map((assignment) => <AssignmentRow key={assignment.id} assignment={assignment} />)}</div>}</CardContent></Card>
</div>; }
function Focus({ icon: Icon, title, text }: { icon: typeof CalendarDays; title: string; text: string }) { return <div className="rounded-2xl border bg-background/50 p-4"><Icon className="size-4 text-primary" /><p className="mt-2 text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p></div>; }
